interface DataType{
   id:number;
   page:string;
   title:string;
   desc:string;
}[];

const faq_data:DataType[]=[
   {
      id:1,
      page:"home_1",
      title:"What are $ECO tokens?",
      desc:"A Solana-based cryptocurrency designed to empower yield through investments in renewable energy assets like solar power. By holding and staking our token, you contribute to sustainable energy projects while earning rewards.",
   },
   {
      id:2,
      page:"home_1",
      title:"How does $ECO generate yeilds?",
      desc:"$ECO token generates yield by allocating funds to profitable energy assets, such as solar farms. The revenue generated from these assets is distributed among token holders as yield, allowing you to earn while supporting green energy initiatives.",
   },
   {
      id:3,
      page:"home_1",
      title:"What did you choose Solana?",
      desc:"We chose Solana due to its high-speed transactions, low fees, and robust security features. This ensures that our token operates efficiently and cost-effectively, providing a seamless experience for our users.",
   },
   {
      id:4,
      page:"home_1",
      title:"How can I earn rewards?",
      desc:"You can earn rewards by staking $EC0 tokens in our platform. Staked tokens are used to fund energy projects, and in return, you receive a share of the profits generated by these assets, distributed regularly as yield.",
   },
   {
      id:5,
      page:"home_1",
      title:"What are environmental effects of $EC0?",
      desc:"By investing in renewable energy assets like solar, $EC0 directly contributes to reducing carbon emissions and promoting sustainable energy sources. Your participation helps accelerate the transition to a greener future.",
   },
   {
      id:6,
      page:"home_1",
      title:"How do I purchase $EC0?",
      desc:"You can purchase $EC0 on decentralized exchanges (DEXs) that support Solana tokens. Simply connect your wallet, select $ECO, and complete your purchase with Solana (SOL) or other supported cryptocurrencies.",
   },
   {
      id:7,
      page:"home_1",
      title:"Is $EC0 secure?",
      desc:"Yes, [Token Name] is built on the Solana blockchain, known for its security and resilience. Additionally, our smart contracts undergo rigorous audits to ensure the safety of your investments and the integrity of the platform.",
   },
   {
      id:1,
      page:"home_2",
      title:"What is blockchain technology?",
      desc:"It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.",
   },
   {
      id:2,
      page:"home_2",
      title:"What is Bitcoin?",
      desc:"It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.",
   },
   {
      id:3,
      page:"home_2",
      title:"Who created Bitcoin?",
      desc:"It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.",
   },
   {
      id:4,
      page:"home_2",
      title:"What is cryptocurrency?",
      desc:"It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.",
   },
   {
      id:5,
      page:"home_2",
      title:"How does cryptocurrency work?",
      desc:"It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.",
   },
];

export default faq_data;